<?php include 'inserts/header.php' ?>
<div class="rightCol">
<!-- 	<div id="rateWrap">
		<h3>Current Rate</h3>
		<h2>&#36;85/hour</h2>
		<p>You will receive an invoice on the first of every month detailing the previous month’s activities, hours associated with each activity, and total billing. I will be happy to discuss and negotiate a specific agreement that meets the individual needs of your organization.</p>
		<a href="../RCSampleInvoice2014.pdf" target="_new">Sample Invoice</a>
	</div> -->
	<img src="images/pen_2.jpg" width="314" height="243" alt="Pen">
</div>
<div class="main">
	<p><span class="bold">Relationships facilitate accountability.</span> I cultivate long-term partnerships with my clients and establish relationships that produce excellent grant proposals at a reasonable cost. My model empowers clients to control their costs while enabling me to develop effective proposals that compellingly reflect the mission, values, and activities of my clients.</p>
	<p><span class="bold">An alternative to the “proposal factory” model.</span> Most grant consulting firms are what I call “proposal factories.” These businesses charge a per-proposal fee, ranging from $400 to $3,000, farming out the actual writing to a network of contractors around the country. Yet the proposals developed in this way rarely reflect the client’s voice, mission, and operations accurately. And the fundraising suffers as a result.</p>
	<p><span class="bold">Ryland Consulting uses an hourly rate.</span> By detailing my work on a line item invoice for each hour, I give my clients a clear understanding of the effort dedicated to their projects. Working together, we can place limits on the number of hours devoted to each project if requested, enabling full control of the pricing structure.</p>
	<p>Upon entering a new client relationship, I develop a custom proposal for the partnership. This proposal identifies promising sources of grant funds, a schedule for approaching grantmakers, and a strategy for soliciting donations from each potential supporter. We will then create an agreement on our fundraising plan that will guide our partnership.</p>
	<p>My goal is to develop long-term partnerships, so your satisfaction is paramount to my success. I cannot guarantee that every proposal will result in funding, but I do guarantee that I will deliver excellent proposals on time.</p>
	<h3 id="RylandConsultingVsTheProposalFactory">Ryland Consulting VS. The Proposal Factory</h3>
	<p>Let’s compare the Ryland Consulting model of hourly billing to a “proposal factory” model that charges a flat rate for each proposal. As I learn a new agency inside and out, I will have to spend fewer and fewer hours on each proposal because I will have already banked a wealth of information on your agency. I won’t have to spend time on each subsequent proposal relearning your agency, like some other consulting firms do.</p>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/static/modules/gviz/1.0/chart.js"> {"dataSourceUrl":"//docs.google.com/spreadsheet/tq?key=0Ane9QvN61ScQdGJERXpEZGduemVBc0h1eWQ4VEpZSFE&transpose=0&headers=1&range=A5%3AC15&gid=0&pub=1","options":{"titleTextStyle":{"bold":true,"color":"#000","fontSize":"14"},"series":[{"pointSize":0,"color":"#6d9eeb","lineWidth":4,"type":"line"},{"color":"#073763","type":"bars"}],"fontName":"Georgia","legendTextStyle":{"color":"#073763","fontSize":12},"animation":{"duration":500},"backgroundColor":{"fill":"#ffffff","fillOpacity":"0"},"width":550,"type":"line","hAxis":{"titleTextStyle":{"color":"#073763","italic":false,"fontSize":12},"title":"Proposals","useFormatFromData":true,"minValue":null,"viewWindowMode":"pretty","textStyle":{"color":"#073763","fontSize":12},"viewWindow":{"min":null,"max":null},"maxValue":null},"vAxes":[{"titleTextStyle":{"color":"#073763","italic":false,"fontSize":12},"useFormatFromData":true,"title":"Cost per Proposal","minValue":0,"viewWindowMode":"pretty","textStyle":{"color":"#073763","fontSize":12},"viewWindow":{"min":0,"max":3000},"gridlines":{"count":"7"},"maxValue":3000},{"useFormatFromData":true,"minValue":null,"viewWindowMode":"pretty","viewWindow":{"min":null,"max":null},"maxValue":null}],"title":"","booleanRole":"certainty","height":323,"interpolateNulls":false,"legend":"right","useFirstColumnAsDomain":true,"tooltip":{}},"state":{},"view":{"columns":[{"calc":"stringify","type":"string","sourceColumn":0},1,2]},"chartType":"ComboChart","chartName":"Chart 1"} </script>
	<p class="caption">This chart represents an example of the long-term cost of a partnership with Ryland Consulting compared to a Proposal Factory. The chart assumes that each proposal is of the same complexity. The actual cost of each proposal will fluctuate, depending on the complexity and length of the proposal. In general, because I will require less and less preparation time as our relationship develops, I will require fewer and fewer hours to develop each proposal.</p>
</div>
<?php include 'inserts/footer.php' ?>